model: resnet50
checkpoint: "output/train/CCE/model_best.pth.tar"
data_dir: "data/small-collomboles/dataset/test"
num_classes: 79

results_dir: "output/test/cce"
results_file: "test_cce"

conf_matrix: True