model: resnet50
checkpoint: "output/train/HCE_0_1/model_best.pth.tar"
data_dir: "data/small-collomboles/dataset/test"
num_classes: 79

results_dir: "output/test/hce_0_1"
results_file: "test_hce_0_1"

conf_matrix: True